### ISSUE TITLE
Typo in Readme.md

### ISSUE THREAD

**Issue by AminTaheri23** [miladfa7/Iranian-politicians-twitter-dataset-persian#1]
Hello, 
Thank you for the awesome Dataset. You can also upload it to Kaggle.com. There was a slight typo in the readme.md file. Twint is an open-source project and it is not the Twitter API and it doesn't use it.

Thank you.

**Comment by miladfa7** [comment]
Hello,
Yes sure, I will upload it to Kaggle.com.
readme.md file edited.
Thank you
